In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../datasets/source_crm/cust_info.csv')

In [3]:
df.head()

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18494 entries, 0 to 18493
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cst_id              18490 non-null  float64
 1   cst_key             18494 non-null  str
 2   cst_firstname       18486 non-null  str
 3   cst_lastname        18487 non-null  str
 4   cst_marital_status  18487 non-null  str
 5   cst_gndr            13916 non-null  str
 6   cst_create_date     18490 non-null  str
dtypes: float64(1), str(6)
memory usage: 1.6 MB

In [8]:
df.columns

Index(['cst_id', 'cst_key', 'cst_firstname', 'cst_lastname',
       'cst_marital_status', 'cst_gndr', 'cst_create_date'],
      dtype='str')

In [9]:
df = pd.read_csv('../datasets/source_crm/prd_info.csv')

In [10]:
df.head()

,prd_id,prd_key,prd_nm,prd_cost,prd_line,prd_start_dt,prd_end_dt
0,210,CO-RF-FR-R92B-58,HL Road Frame - Black- 58,NaN,R,2003-07-01,NaN
1,211,CO-RF-FR-R92R-58,HL Road Frame - Red- 58,NaN,R,2003-07-01,NaN
2,212,AC-HE-HL-U509-R,Sport-100 Helmet- Red,12.0,S,2011-07-01,2007-12-28
3,213,AC-HE-HL-U509-R,Sport-100 Helmet- Red,14.0,S,2012-07-01,2008-12-27
4,214,AC-HE-HL-U509-R,Sport-100 Helmet- Red,13.0,S,2013-07-01,NaN

In [11]:
df.columns

Index(['prd_id', 'prd_key', 'prd_nm', 'prd_cost', 'prd_line', 'prd_start_dt',
       'prd_end_dt'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   prd_id        397 non-null    int64
 1   prd_key       397 non-null    str
 2   prd_nm        397 non-null    str
 3   prd_cost      395 non-null    float64
 4   prd_line      380 non-null    str
 5   prd_start_dt  397 non-null    str
 6   prd_end_dt    200 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 42.9 KB

In [13]:
df = pd.read_csv('../datasets/source_crm/sales_details.csv')

In [14]:
df.head()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price
0,SO43697,BK-R93R-62,21768,20101229,20110105,20110110,3578.0,1,3578.0
1,SO43698,BK-M82S-44,28389,20101229,20110105,20110110,3400.0,1,3400.0
2,SO43699,BK-M82S-44,25863,20101229,20110105,20110110,3400.0,1,3400.0
3,SO43700,BK-R50B-62,14501,20101229,20110105,20110110,699.0,1,699.0
4,SO43701,BK-M82S-44,11003,20101229,20110105,20110110,3400.0,1,3400.0

In [15]:
df = pd.read_csv('../datasets/source_erp/CUST_AZ12.csv')

In [16]:
df.head()

             CID       BDATE     GEN
0  NASAW00011000  1971-10-06    Male
1  NASAW00011001  1976-05-10    Male
2  NASAW00011002  1971-02-09    Male
3  NASAW00011003  1973-08-14  Female
4  NASAW00011004  1979-08-05  Female

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18484 entries, 0 to 18483
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CID     18484 non-null  str
 1   BDATE   18484 non-null  str
 2   GEN     17012 non-null  str
dtypes: str(3)
memory usage: 911.8 KB

In [18]:
df = pd.read_csv('../datasets/source_erp/loc_a101.csv')

In [19]:
df.head()

           CID      CNTRY
0  AW-00011000  Australia
1  AW-00011001  Australia
2  AW-00011002  Australia
3  AW-00011003  Australia
4  AW-00011004  Australia

In [22]:
df = pd.read_csv('../datasets/source_crm/sales_details.csv')

In [23]:
df.head()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price
0,SO43697,BK-R93R-62,21768,20101229,20110105,20110110,3578.0,1,3578.0
1,SO43698,BK-M82S-44,28389,20101229,20110105,20110110,3400.0,1,3400.0
2,SO43699,BK-M82S-44,25863,20101229,20110105,20110110,3400.0,1,3400.0
3,SO43700,BK-R50B-62,14501,20101229,20110105,20110110,699.0,1,699.0
4,SO43701,BK-M82S-44,11003,20101229,20110105,20110110,3400.0,1,3400.0

In [24]:
df = pd.read_csv('../datasets/source_erp/px_cat_g1v2.csv')

In [25]:
df.head()

      ID          CAT             SUBCAT MAINTENANCE
0  AC_BR  Accessories         Bike Racks         Yes
1  AC_BS  Accessories        Bike Stands          No
2  AC_BC  Accessories  Bottles and Cages          No
3  AC_CL  Accessories           Cleaners         Yes
4  AC_FE  Accessories            Fenders          No